server:
  servlet:
    context-path: '/active/api'
  port: 8627

kontur:
  platform:
    event-api:
      url: 'https://apps.kontur.io/events/'
      connectionTimeout: 60
      pageSize: 1000
      readTimeout: 60
    keycloak:
      url: 'https://keycloak01.kontur.io/auth'
      realm: 'kontur'
      username: 'username' #Kontur's account name
      password: 'password' #Kontur's account password
      clientId: 'kontur_platform'
    kcApi:
      url: 'https://api.kontur.io/layers'
      pageSize: 1000
      connectionTimeout: 60
      readTimeout: 60
    layersApi:
      url: 'https://api.kontur.io/layers/v2'
      pageSize: 1000
      connectionTimeout: 60
      readTimeout: 60
    insightsApi:
      url: 'https://apps.kontur.io/insights-api'
      connectionTimeout: 60
      readTimeout: 60
    tiles:
      host: 'https://disaster.ninja'
    userProfileApi:
      url: 'https://apps.kontur.io/userprofile/'
      connectionTimeout: 20
      readTimeout: 20
    llmAnalyticsApi:
      url: 'https://apps.kontur.io/insights-llm-api'
      connectionTimeout: 20
      readTimeout: 240

notifications:
  enabled: false
  slack:
    enabled: false
  slack2:
    enabled: false
  slackWebHook: ''
  slackWebHook2: ''
  feed: ''
  feed2: ''
  email:
    enabled: false

springdoc:
  writer-with-default-pretty-printer: true
  swagger-ui:
    path: 'doc'
    disable-swagger-default-url: true
    tags-sorter: alpha
    operations-sorter: alpha

management:
  metrics:
    export:
      simple:
        enabled: false
    distribution:
      percentiles-histogram:
        http.server.requests: true
        http.client.requests: true
  health:
    ping:
      enabled: false
    diskspace:
      enabled: false
    refresh:
      enabled: false
  endpoint:
    health:
      probes:
        enabled: true
      status:
        http-mapping:
          down: 200
      cache:
        time-to-live: 10s
      show-details: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
      base-path: /
      path-mapping:
        prometheus: metrics

spring:
  config:
    import:
      - classpath:/analytics/analyticstabconfig.yaml
      - classpath:/analytics/notificationsanalyticsconfig.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak01.kontur.io/realms/kontur
          jwk-set-uri: https://keycloak01.kontur.io/realms/kontur/protocol/openid-connect/certs
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    default-property-inclusion: non_null
  thymeleaf:
    prefix: classpath:/notification/
    cache: false
    encoding: UTF-8

graphql:
  apollo:
    maxIdleConnections: 100
    keepAliveDuration: 300
    connectionTimeout: 300
    readTimeout: 300

sentry:
  dsn: https://fixme@dsn.ingest.sentry.io/project-id
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
  # We recommend adjusting this value in production.
  traces-sample-rate: 1.0
