layers:
  configs:
    ##### Category: NONE
    ### Group: Layers in selected area

    ## Event Shape: default config
    - id: 'eventShape'
      globalOverlay: false
      displayLegendIfNoFeaturesExist: true
      name: 'Event shape'
      group: 'Layers in selected area'
      legend:
        type: 'simple'
        steps:
          - stepName: 'Exposure Area'
            style:
              line-width: '3px'
              line-color: '#051626'

    ## Event Shape: configs per event type
    - id: 'eventShape.CYCLONE'
      globalOverlay: false
      displayLegendIfNoFeaturesExist: false
      name: 'Event shape'
      group: 'Layers in selected area'
      legend:
        type: 'simple'
        steps:
          - stepName: 'Centroid'
            paramName: 'Class'
            paramValue: 'Point_Centroid'
            style:
              fill: '#051626'
              line-width: 3px
              line-color: '#fff'
          - stepName: 'Exposure Area 60 km/h'
            paramName: 'Class'
            paramValue: 'Poly_Green'
            style:
              line-width: 3px
              line-color: '#F5A663'
          - stepName: 'Exposure Area 90 km/h'
            paramName: 'Class'
            paramValue: 'Poly_Orange'
            style:
              line-width: 3px
              line-color: '#DA5080'
          - stepName: 'Exposure Area 120 km/h'
            paramName: 'Class'
            paramValue: 'Poly_Red'
            style:
              line-width: 2px
              line-color: '#830909'
          - stepName: 'Line Track'
            paramName: 'Class'
            paramValue: 'Line_Line_[0-9]+'
            style:
              color: '#8C949B'
          - stepName: 'Point Track'
            paramName: 'Class'
            paramValue: 'Point_Polygon_Point_[0-9]+'
            style:
              color: '#8C949B'
          - stepName: 'Uncertainty Cones'
            paramName: 'Class'
            paramValue: 'Poly_Cones'
            style:
              line-width: 1px
              line-color: '#646F78'

    - id: 'eventShape.DROUGHT'
      globalOverlay: false
      displayLegendIfNoFeaturesExist: false
      name: 'Event shape'
      group: 'Layers in selected area'
      legend:
        type: 'simple'
        steps:
          - stepName: 'Centroid'
            paramName: 'Class'
            paramValue: 'Point_Centroid'
            style:
              fill: '#051626'
              line-width: 3px
              line-color: '#fff'
          - stepName: 'Exposure Area'
            paramName: 'Class'
            paramValue: 'Poly_area'
            style:
              line-width: 3px
              line-color: '#051626'

    - id: 'eventShape.EARTHQUAKE'
      globalOverlay: false
      displayLegendIfNoFeaturesExist: false
      name: 'Event shape'
      group: 'Layers in selected area'
      legend:
        type: 'simple'
        steps:
          - stepName: 'Centroid'
            paramName: 'Class'
            paramValue: 'Point_Centroid'
            style:
              fill: '#051626'
              line-width: 3px
              line-color: '#fff'
          - stepName: 'Exposure Area 100km'
            paramName: 'Class'
            paramValue: 'Poly_Circle'
            style:
              line-width: 3px
              line-color: '#646F78'

    - id: 'eventShape.FLOOD'
      globalOverlay: false
      displayLegendIfNoFeaturesExist: false
      name: 'Event shape'
      group: 'Layers in selected area'
      legend:
        type: 'simple'
        steps:
          - stepName: 'Centroid'
            paramName: 'Class'
            paramValue: 'Point_Centroid'
            style:
              fill: '#051626'
              line-width: 3px
              line-color: '#fff'
          - stepName: 'Exposure Area'
            paramName: 'Class'
            paramValue: 'Poly_Affected'
            style:
              line-width: 3px
              line-color: '#051626'
          - stepName: 'Alert Area'
            paramName: 'Class'
            paramValue: 'Poly_Global'
            style:
              line-width: 2px
              line-color: '#051626'
              line-opacity: 50%

    - id: 'eventShape.WILDFIRE'
      globalOverlay: false
      displayLegendIfNoFeaturesExist: false
      name: 'Event shape'
      group: 'Layers in selected area'
      legend:
        type: 'simple'
        steps:
          - stepName: 'Centroid'
            paramName: 'Class'
            paramValue: 'Point_Centroid'
            style:
              fill: '#051626'
              line-width: 3px
              line-color: '#fff'
          - stepName: 'Exposure Area'
            paramName: 'Class'
            paramValue: 'Poly_area'
            style:
              line-width: 3px
              line-color: '#051626'

    - id: 'eventShape.VOLCANO'
      globalOverlay: false
      displayLegendIfNoFeaturesExist: false
      name: 'Event shape'
      group: 'Layers in selected area'
      legend:
        type: 'simple'
        steps:
          - stepName: 'Centroid'
            paramName: 'Class'
            paramValue: 'Point_Centroid'
            style:
              fill: '#051626'
              line-width: 3px
              line-color: '#fff'
          - stepName: 'Exposure Area 100Km'
            paramName: 'Class'
            paramValue: 'Poly_Circle'
            style:
              line-width: 3px
              line-color: '#051626'
          - stepName: 'Exposure Area'
            paramName: 'Class'
            paramValue: 'Poly_Cones_0'
            style:
              line-width: 3px
              line-color: '#051626'
          - stepName: '6 hours Forecast'
            paramName: 'Class'
            paramValue: 'Poly_Cones_6'
            style:
              line-width: 2px
              line-color: '#051626'
              line-opacity: 70%
          - stepName: '12 hours Forecast'
            paramName: 'Class'
            paramValue: 'Poly_Cones_12'
            style:
              line-width: 2px
              line-color: '#051626'
              line-opacity: 50%
          - stepName: '18 hours Forecast'
            paramName: 'Class'
            paramValue: 'Poly_Cones_18'
            style:
              line-width: 2px
              line-color: '#051626'
              line-opacity: 30%

    # --- empty template ---
    #- id: 'eventShape.'
    #  globalOverlay: false
    #  displayLegendIfNoFeaturesExist: false
    #  name: 'Event shape'
    #  group: 'Layers in selected area'
    #  legend:
    #    type: 'simple'
    #    steps:
    #      - stepName: 'Centroid'
    #        paramName: 'Class'
    #        paramValue: 'Point_Centroid'
    #        paramValue: 'Poly_area'
    #        paramValue: 'Poly_Circle'
    #        paramValue: 'Poly_Affected'
    #        paramValue: 'Poly_Global'
    #        style:
    #          fill: '#051626'
    #          line-width: 3px
    #          line-color: '#fff'
    #          line-opacity: 50%
    #          color: '#fff'

    ##end of Event Shape

    - id: 'kontur_urban_core'
      globalOverlay: true
      displayLegendIfNoFeaturesExist: true
      group: 'Layers in selected area'
      copyright: '© Kontur'
      legend:
        type: 'simple'
        steps:
          - stepShape: 'hex'
            style:
              color: '#FF7B00'
              width: 3
              offset: 4
              casing-offset: 2
              casing-color: '#FF7B00'
              casing-width: 3
              casing-opacity: 0.5
    - id: 'kontur_settled_periphery'
      globalOverlay: true
      displayLegendIfNoFeaturesExist: true
      group: 'Layers in selected area'
      copyright: '© Kontur'
      legend:
        type: 'simple'
        steps:
          - stepShape: 'hex'
            style:
              color: '#2AD72A'
              width: 3
              casing-offset: 2
              casing-color: '#2AD72A'
              casing-width: 3
              casing-opacity: 0.5

    ##### Category: OVERLAY
    ### Group: Kontur
    - id: 'activeContributors'
      globalOverlay: true
      displayLegendIfNoFeaturesExist: true #can't be filtered until MVT tiles are read
      name: 'Active contributors'
      category: 'overlay'
      group: 'Kontur'
      description: 'Contributors are labeled as active based on their mapping activity in the area for the past 2 years. We consider OpenStreetMap users to be local and mark them green if most of their edits were made close to that area.'
      copyright: '© OpenStreetMap Contributors, © Kontur'
      source:
        type: 'vector'
        url: '{tilesHost}/tiles/stats/{x}/{y}/{z}.mvt'
        tileSize: 512
      legend:
        type: 'simple'
        steps:
          - stepName: 'Possibly local mappers'
            stepShape: 'circle'
            text: '{top_user}'
            paramName: 'is_local'
            paramValue: true
            style:
              color: #009100 #todo use icon instead
          - stepName: 'Active mappers'
            stepShape: 'circle'
            text: '{top_user}'
            paramName: 'is_local'
            paramValue: false
            style:
              color: #434343 #todo use icon instead

    - id: 'hotProjects'
      globalOverlay: true
      displayLegendIfNoFeaturesExist: false
      name: 'Hot Projects'
      description: 'Projects on HOT Tasking Manager, ongoing and historical'
      category: 'overlay'
      group: 'Kontur'
      copyright: '© Humanitarian OpenStreetMap Team, © Kontur'
      legend:
        type: 'simple'
        steps:
          - stepName: 'Published'
            stepShape: 'circle'
            paramName: 'status'
            paramValue: 'Published'
            style:
              icon: 'link_to_icon_2'
          - stepName: 'Archived'
            stepShape: 'circle'
            paramName: 'status'
            paramValue: 'Archived'
            style:
              icon: 'link_to_icon_3'

    ### Group: Kontur Analytical Layers
    - id: 'Kontur OpenStreetMap Quantity'
      globalOverlay: true
      name: 'OSM Object Quantity'
      category: 'overlay'
      group: 'Kontur Analytical Layers'
      type: 'bivariate'
      copyrights: #todo
      source:
        type: 'vector'
        url: '{tilesHost}/tiles/stats/{x}/{y}/{z}.mvt'
        tileSize: 512
    - id: 'Kontur OpenStreetMap Building Quantity'
      globalOverlay: true
      name: 'OSM Building Quantity'
      category: 'overlay'
      group: 'Kontur Analytical Layers'
      type: 'bivariate'
      copyrights: #todo
      source:
        type: 'vector'
        url: '{tilesHost}/tiles/stats/{x}/{y}/{z}.mvt'
        tileSize: 512
    - id: 'Kontur OpenStreetMap Road Length'
      globalOverlay: true
      name: 'OSM Road Length'
      category: 'overlay'
      group: 'Kontur Analytical Layers'
      type: 'bivariate'
      copyrights: #todo
      source:
        type: 'vector'
        url: '{tilesHost}/tiles/stats/{x}/{y}/{z}.mvt'
        tileSize: 512
    - id: 'Kontur OpenStreetMap Mapping Activity'
      globalOverlay: true
      name: 'OSM Mapping Activity'
      category: 'overlay'
      group: 'Kontur Analytical Layers'
      type: 'bivariate'
      copyrights: #todo
      source:
        type: 'vector'
        url: '{tilesHost}/tiles/stats/{x}/{y}/{z}.mvt'
        tileSize: 512
    - id: 'Kontur OpenStreetMap Antiquity'
      globalOverlay: true
      name: 'OSM Antiquity'
      category: 'overlay'
      group: 'Kontur Analytical Layers'
      type: 'bivariate'
      copyrights: #todo
      source:
        type: 'vector'
        url: '{tilesHost}/tiles/stats/{x}/{y}/{z}.mvt'
        tileSize: 512
    - id: 'Kontur Nighttime Heatwave Risk'
      globalOverlay: true
      name: 'Kontur Nighttime Heatwave Risk'
      category: 'overlay'
      group: 'Kontur Analytical Layers'
      type: 'bivariate'
      copyrights: #todo
      source:
        type: 'vector'
        url: '{tilesHost}/tiles/stats/{x}/{y}/{z}.mvt'
        tileSize: 512
  ##### Category: BASELINE
