configs:
  ##### Category: NONE
  ### Group: Layers in selected area

  ## Event Shape: default config
  - id: 'eventShape'
    globalOverlay: false
    displayLegendIfNoFeaturesExist: true
    boundaryRequiredForRetrieval: false
    eventIdRequiredForRetrieval: true
    name: 'Event shape'
    group: 'layersInSelectedArea'
    legend:
      name: 'Event shape'
      type: 'simple'
      steps:
        - stepName: 'Exposure Area'
          stepShape: 'circle'
          style:
            width: 3
            color: '#051626'

  ## Event Shape: configs per event type
  - id: 'eventShape.CYCLONE'
    globalOverlay: false
    displayLegendIfNoFeaturesExist: false
    boundaryRequiredForRetrieval: false
    eventIdRequiredForRetrieval: true
    name: 'Event shape'
    group: 'layersInSelectedArea'
    legend:
      name: 'Event shape'
      type: 'simple'
      steps:
        - stepName: 'Centroid'
          stepShape: 'circle'
          paramName: 'areaType'
          paramValue: 'centerPoint'
          style:
            circle-radius: 3
            circle-color: '#051626'
        - stepName: 'Exposure Area 60 km/h'
          stepShape: 'circle'
          paramName: 'Class'
          paramValue: 'Poly_Green'
          style:
            width: 2
            color: '#FFAB2E'
            offset: 4
            casing-offset: 2
            casing-color: '#FFAB2E'
            casing-width: 3
            casing-opacity: 0.3
          order: 100
        - stepName: 'Exposure Area 90 km/h'
          stepShape: 'circle'
          paramName: 'Class'
          paramValue: 'Poly_Orange'
          style:
            width: 2
            color: '#FC4C00'
            offset: 4
            casing-offset: 2
            casing-color: '#FC4C00'
            casing-width: 3
            casing-opacity: 0.3
          order: 110
        - stepName: 'Exposure Area 120 km/h'
          stepShape: 'circle'
          paramName: 'Class'
          paramValue: 'Poly_Red'
          style:
            width: 2
            color: '#830909'
            offset: 4
            casing-offset: 2
            casing-color: '#830909'
            casing-width: 3
            casing-opacity: 0.3
          order: 120
        - stepName: 'Line Track'
          stepShape: 'circle'
          paramName: 'areaType'
          paramValue: 'track'
          style:
            color: '#8C949B'
        - stepName: 'Point Track'
          stepShape: 'circle'
          paramName: 'areaType'
          paramValue: 'position'
          style:
            circle-radius: 2
            circle-color: '#051626'
        - stepName: 'Uncertainty Cones'
          stepShape: 'circle'
          paramName: 'Class'
          paramValue: 'Poly_Cones'
          style:
            width: 1
            color: '#646F78'
        - stepName: 'Exposure Area'
          stepShape: 'circle'
          paramName: 'areaType'
          paramValue: 'globalArea'
          style:
            width: 1
            color: '#051626'

  - id: 'eventShape.DROUGHT'
    globalOverlay: false
    displayLegendIfNoFeaturesExist: false
    boundaryRequiredForRetrieval: false
    eventIdRequiredForRetrieval: true
    name: 'Event shape'
    group: 'layersInSelectedArea'
    legend:
      name: 'Event shape'
      type: 'simple'
      steps:
        - stepName: 'Centroid'
          stepShape: 'circle'
          paramName: 'areaType'
          paramValue: 'centerPoint'
          style:
            circle-radius: 3
            circle-color: '#051626'
        - stepName: 'Exposure Area'
          stepShape: 'circle'
          paramName: 'areaType'
          paramPattern: 'globalArea|exposure'
          paramValue: 'globalArea'
          style:
            width: 3
            color: '#051626'

  - id: 'eventShape.EARTHQUAKE'
    globalOverlay: false
    displayLegendIfNoFeaturesExist: false
    boundaryRequiredForRetrieval: false
    eventIdRequiredForRetrieval: true
    name: 'Event shape'
    group: 'layersInSelectedArea'
    legend:
      name: 'Event shape'
      type: 'simple'
      steps:
        - stepName: 'Centroid'
          stepShape: 'circle'
          paramName: 'areaType'
          paramValue: 'centerPoint'
          style:
            circle-radius: 3
            circle-color: '#051626'
        - stepName: 'Exposure Area 100 km'
          stepShape: 'circle'
          paramName: 'areaType'
          paramValue: 'alertArea'
          style:
            width: 3
            color: '#646F78'
        - stepName: 'Intensity III'
          stepShape: 'circle'
          paramName: 'Class'
          paramValue: 'Poly_SMPInt_3'
          style:
            width: 3
            color: '#EAED41'
            offset: 4
            casing-offset: 2
            casing-color: '#EAED41'
            casing-width: 3
            casing-opacity: 0.3
        - stepName: 'Intensity IV'
          stepShape: 'circle'
          paramName: 'Class'
          paramValue: 'Poly_SMPInt_4'
          style:
            width: 2
            color: '#FACD2D'
            offset: 4
            casing-offset: 2
            casing-color: '#FACD2D'
            casing-width: 3
            casing-opacity: 0.3
        - stepName: 'Intensity V'
          stepShape: 'circle'
          paramName: 'Class'
          paramValue: 'Poly_SMPInt_5'
          style:
            width: 2
            color: '#FFAB2E'
            offset: 4
            casing-offset: 2
            casing-color: '#FFAB2E'
            casing-width: 3
            casing-opacity: 0.3
        - stepName: 'Intensity VI'
          stepShape: 'circle'
          paramName: 'Class'
          paramValue: 'Poly_SMPInt_6'
          style:
            width: 2
            color: '#FF7C1D'
            offset: 4
            casing-offset: 2
            casing-color: '#FF7C1D'
            casing-width: 3
            casing-opacity: 0.3
        - stepName: 'Intensity VII'
          stepShape: 'circle'
          paramName: 'Class'
          paramValue: 'Poly_SMPInt_7'
          style:
            width: 2
            color: '#FC4C00'
            offset: 4
            casing-offset: 2
            casing-color: '#FC4C00'
            casing-width: 3
            casing-opacity: 0.3
        - stepName: 'Intensity VIII'
          stepShape: 'circle'
          paramName: 'Class'
          paramValue: 'Poly_SMPInt_8'
          style:
            width: 2
            color: '#DF2100'
            offset: 4
            casing-offset: 2
            casing-color: '#DF2100'
            casing-width: 3
            casing-opacity: 0.3
        - stepName: 'Intensity IX'
          stepShape: 'circle'
          paramName: 'Class'
          paramValue: 'Poly_SMPInt_9'
          style:
            width: 2
            color: '#830909'
            offset: 4
            casing-offset: 2
            casing-color: '#830909'
            casing-width: 3
            casing-opacity: 0.3
        - stepName: 'Intensity X'
          stepShape: 'circle'
          paramName: 'Class'
          paramValue: 'Poly_SMPInt_10'
          style:
            width: 2
            color: '#470A00'
            offset: 4
            casing-offset: 2
            casing-color: '#470A00'
            casing-width: 3
            casing-opacity: 0.3

  - id: 'eventShape.FLOOD'
    globalOverlay: false
    displayLegendIfNoFeaturesExist: false
    boundaryRequiredForRetrieval: false
    eventIdRequiredForRetrieval: true
    name: 'Event shape'
    group: 'layersInSelectedArea'
    legend:
      name: 'Event shape'
      type: 'simple'
      steps:
        - stepName: 'Centroid'
          stepShape: 'circle'
          paramName: 'areaType'
          paramValue: 'centerPoint'
          style:
            circle-radius: 3
            circle-color: '#051626'
        - stepName: 'Exposure Area'
          stepShape: 'circle'
          paramName: 'areaType'
          paramPattern: 'position|exposure'
          paramValue: 'exposure'
          style:
            width: 3
            color: '#051626'
        - stepName: 'Alert Area'
          stepShape: 'circle'
          paramName: 'areaType'
          paramPattern: 'globalArea|alertArea'
          paramValue: 'globalArea'
          style:
            width: 2
            color: '#051626'
            opacity: 0.5

  - id: 'eventShape.WILDFIRE'
    globalOverlay: false
    displayLegendIfNoFeaturesExist: false
    boundaryRequiredForRetrieval: false
    eventIdRequiredForRetrieval: true
    name: 'Event shape'
    group: 'layersInSelectedArea'
    legend:
      name: 'Event shape'
      type: 'simple'
      steps:
        - stepName: 'Centroid'
          stepShape: 'circle'
          paramName: 'areaType'
          paramValue: 'centerPoint'
          style:
            circle-radius: 3
            circle-color: '#051626'
        - stepName: 'Start point'
          stepShape: 'circle'
          paramName: 'areaType'
          paramValue: 'startPoint'
          style:
            circle-radius: 3
            circle-color: '#051626'
        - stepName: 'Exposure Area'
          stepShape: 'circle'
          paramName: 'areaType'
          paramValue: 'exposure'
          style:
            width: 3
            color: '#051626'
        - stepName: 'Alert Area'
          stepShape: 'circle'
          paramName: 'areaType'
          paramValue: 'alertArea'
          style:
            width: 3
            color: '#051626'

  - id: 'eventShape.VOLCANO'
    globalOverlay: false
    displayLegendIfNoFeaturesExist: false
    boundaryRequiredForRetrieval: false
    eventIdRequiredForRetrieval: true
    name: 'Event shape'
    group: 'layersInSelectedArea'
    legend:
      name: 'Event shape'
      type: 'simple'
      steps:
        - stepName: 'Centroid'
          stepShape: 'circle'
          paramName: 'areaType'
          paramValue: 'centerPoint'
          style:
            circle-radius: 3
            circle-color: '#051626'
        - stepName: 'Exposure Area 100 km'
          stepShape: 'circle'
          paramName: 'areaType'
          paramValue: 'alertArea'
          style:
            width: 3
            color: '#051626'
        - stepName: 'Initial Forecast'
          stepShape: 'circle'
          paramName: 'forecastHrs'
          paramValue: 0
          style:
            width: 2
            color: '#051626'
            opacity: 0.8
        - stepName: '6 hours Forecast'
          stepShape: 'circle'
          paramName: 'forecastHrs'
          paramValue: 6
          style:
            width: 2
            color: '#051626'
            opacity: 0.6
        - stepName: '12 hours Forecast'
          stepShape: 'circle'
          paramName: 'forecastHrs'
          paramValue: 12
          style:
            width: 2
            color: '#051626'
            opacity: 0.4
        - stepName: '18 hours Forecast'
          stepShape: 'circle'
          paramName: 'forecastHrs'
          paramValue: 18
          style:
            width: 2
            color: '#051626'
            opacity: 0.2
        - stepName: 'Initial Forecast'
          stepShape: 'circle'
          paramName: 'Class'
          paramValue: 'Poly_Cones_0'
          style:
            width: 2
            color: '#051626'
            opacity: 0.8

  # --- empty template ---
  #- id: 'eventShape.'
  #  globalOverlay: false
  #  displayLegendIfNoFeaturesExist: false
  #  boundaryRequiredForRetrieval: false
  #  eventIdRequiredForRetrieval: true
  #  name: 'Event shape'
  #  group: 'layersInSelectedArea'
  #  legend:
  #    type: 'simple'
  #    steps:
  #      - stepName: 'Centroid'
  #        paramName: 'Class'
  #        paramValue: 'Point_Centroid'
  #        paramValue: 'Poly_area'
  #        paramValue: 'Poly_Circle'
  #        paramValue: 'Poly_Affected'
  #        paramValue: 'Poly_Global'
  #        style:
  #          fill-color: '#051626'
  #          width: 3
  #          color: '#fff'

  ##end of Event Shape

  - id: 'kontur_urban_core'
    globalOverlay: false
    name: "Kontur Urban Core"
    displayLegendIfNoFeaturesExist: true
    boundaryRequiredForRetrieval: true
    group: 'layersInSelectedArea'
    copyrights:
      - '© Kontur'
    legend:
      name: "Kontur Urban Core"
      type: 'simple'
      steps:
        - stepShape: 'hex'
          style:
            color: '#FF7B00'
            width: 3
            offset: 4
            casing-offset: 2
            casing-color: '#FF7B00'
            casing-width: 3
            casing-opacity: 0.5
  - id: 'kontur_settled_periphery'
    globalOverlay: false
    name: "Kontur Settled Periphery"
    displayLegendIfNoFeaturesExist: true
    boundaryRequiredForRetrieval: true
    group: 'layersInSelectedArea'
    copyrights:
      - '© Kontur'
    legend:
      type: 'simple'
      steps:
        - stepShape: 'hex'
          style:
            color: '#2AD72A'
            width: 3
            casing-offset: 2
            casing-color: '#2AD72A'
            casing-width: 3
            casing-opacity: 0.5

  ##### Category: OVERLAY
  ### Group: Kontur
  - id: 'activeContributors'
    minZoom: 0
    maxZoom: 8
    globalOverlay: true
    displayLegendIfNoFeaturesExist: true #can't be filtered until MVT tiles are read
    boundaryRequiredForRetrieval: false
    eventIdRequiredForRetrieval: false
    name: 'Active contributors'
    description: 'Contributors are labeled as active based on their mapping activity in the area for the past 2 years. We consider OpenStreetMap users to be local and mark them green if most of their edits were made close to that area.'
    copyrights:
      - '© OpenStreetMap Contributors, © Kontur'
    source:
      type: 'vector'
      urls:
        - '{tilesHost}/tiles/users/{z}/{x}/{y}.mvt'
      tileSize: 512
    legend:
      name: 'Active contributors'
      type: 'simple'
      linkProperty: 'profile'
      steps:
        - stepName: 'Possibly local mappers'
          sourceLayer: 'users'
          stepShape: 'circle'
          paramName: 'is_local'
          paramValue: true
          style:
            text: '{top_user}'
            text-color: 'rgb(0, 145, 0)'
            text-halo-color: 'rgba(255, 255, 255, 0.3)'
            text-halo-radius: 1
            text-size: 14
            text-letter-spacing: 0.05
            text-padding: 0
            font-family: 'Noto Sans Bold'
            icon-image: 'osm-user-shield'
            icon-text-fit: 'both'
            icon-allow-overlap: true
            symbol-placement: 'point'
            max-width: 3
        - stepName: 'Active mappers'
          sourceLayer: 'users'
          stepShape: 'circle'
          paramName: 'is_local'
          paramValue: false
          style:
            text: '{top_user}'
            text-color: 'rgb(100, 111, 120)'
            text-halo-color: 'rgba(255, 255, 255, 0.3)'
            text-halo-radius: 1
            text-size: 12
            text-letter-spacing: 0.05
            text-padding: 0
            font-family: 'Noto Sans Regular'
            icon-image: 'osm-user-shield'
            icon-text-fit: 'both'
            icon-allow-overlap: true
            symbol-placement: 'point'
            max-width: 3
        - sourceLayer: 'hexagon'
          style:
            color: 'black'
            width: 1
            opacity: 0.2
